#!/usr/bin/env python3

import os
import sys
import argparse
import logging
import commons
import directory

"""
DodgyNet is a peer to peer file file sharing program that implements the 
DodgyNet protocol using the Happy Tracker and Puncher protocols to achieve
a fair and efficient file sharing. We designed the P2P system to work over
Private IP/NAT using the Puncher protocol to punch through the firewall
and/or NAT.
"""

possible_actions = ["upload", "join", "list", "query", "download"]

def main(arguments):

    logging.basicConfig(level=logging.DEBUG, format=commons.logger_format)

    parser = argparse.ArgumentParser(
            description=__doc__,
            formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('action', help="Action to be performed, possible actions: %s" % ', '.join(possible_actions), 
            type=str, choices=possible_actions, metavar='action')
    parser.add_argument('-f', '--file', help="Target file to download from the"
            " directory server.", 
            default=sys.stdin, type=argparse.FileType('r'))
    parser.add_argument('-s', '--server', help="Address of the server",
            type=str, default="e2empire.com")

    args = parser.parse_args(arguments)

    logger = logging.getLogger()
    logger.info(args)

    if args.action == "list":
        logger.debug("Listing files from the server.")
        dir_client = directory.DirClient()
        dir_client.list()
        dir_client.bye()
    else:
        print("stub")

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))

# vim: expandtab shiftwidth=4 softtabstop=4 textwidth=80:
